#!/bin/bash

_export_envs() {
  export SERVER_PORT=8080
}

__build() {
  _export_envs
  docker build --build-arg="SERVER PORT=\"${SERVER_PORT}\"" -f Dockerfile.metadata-service -t metadata-service .
}

_deploy_db() {
  kubectl apply -f k8s/db.yaml
}

_deploy_api() {
  kubectl apply -f k8s/api.yaml
}

__deploy() {
  _create_secrets
  _deploy_db
  sleep 10s
  _deploy_api
}

_create_secrets() {
  kubectl apply -f k8s/secrets.yml
}

usage_message="Usage $0 <command>\nCommands:"

CMD=${1:-}
shift || true
if __${CMD} "$@"; then ## Functions to be called as commands are prefixed with __
  exit 0
else
  echo -e "$usage_message\n$(declare -F | sed -n "s/declare -f __/ - /p")"
fi
