apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service-api
  labels:
    app: metadata-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-service-api
  template:
    metadata:
      labels:
        app: metadata-service-api
    spec:
      containers:
        - name: metadata-service-api
          image: mrinal2196/metadata-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              valueFrom:
                - configMapKeyRef:
                    name: api-config
                    key: SERVER_PORT
            - name: DB_URI
              valueFrom:
                - configMapKeyRef:
                    name: api-config
                    key: DB_URI
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service-api
spec:
  selector:
    app: metadata-service-api
  ports:
    - name: "server-port-8080"
      protocol: TCP
      port: 8080
      targetPort: 8080