apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service-api
  labels:
    app: metadata-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-service-api
  template:
    metadata:
      labels:
        app: metadata-service-api
    spec:
      containers:
        - name: metadata-service-api
          image: mrinal2196/metadata-service:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DB_URI
              value: "mongodb://metadata-service-db:27017/metadata"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service-api
spec:
  selector:
    app: metadata-service-api
  ports:
    - name: "server-port-8080"
      protocol: TCP
      port: 8080
      targetPort: 8080