apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service-db
  labels:
    app: metadata-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-service-db
  template:
    metadata:
      labels:
        app: metadata-service-db
    spec:
      containers:
        - name: metadata-service-db
          image: mongo:3.4-xenial
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_USERNAME
              value: "metadata-service"
            - name: DATABASE_PASSWORD
              value: "rotc"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service-db
spec:
  selector:
    app: metadata-service-db
  ports:
    - name: DB-PORT-27017
      protocol: TCP
      port: 27017
      targetPort: 27017